version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    environment:
      - FRONT_ENVOY_YAML
    networks:
      - envoymesh
    ports:
      - "8000:8000"
      - "8443:8443"


  ext_authz-grpc-service:
    build:
      context: ./auth
      dockerfile: grpc-service/Dockerfile
    networks:
      - envoymesh


  upstream-service:
    build:
      context: ./upstream
      dockerfile: service/Dockerfile
    networks:
      - envoymesh

networks:
  envoymesh: {}
