name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build auth/grpc-service
      working-directory: ./auth/grpc-service
      run: go build -v ./...

    - name: Test auth/grpc-service
      working-directory: ./auth/grpc-service
      run: go test -v ./...
